use southwind;
CREATE TABLE BANK_ACCOUNT (
    ACC_NO INT PRIMARY KEY,
    NAME VARCHAR(50),
    BALANCE DECIMAL(10,2)
);
INSERT INTO BANK_ACCOUNT VALUES
(101, 'Ammu', 15000),
(102, 'Abhi', 7000),
(103, 'Sehan',6000);

SELECT * FROM BANK_ACCOUNT;
START TRANSACTION;
UPDATE BANK_ACCOUNT
SET BALANCE = BALANCE - 1000
WHERE ACC_NO = 102;

UPDATE BANK_ACCOUNT
SET BALANCE = BALANCE + 1000
WHERE ACC_NO = 101;
SELECT * FROM BANK_ACCOUNT;
 
 Rollback;
 SELECT * FROM BANK_ACCOUNT;
-- we do the transaction again but this time we commit
START TRANSACTION;

UPDATE BANK_ACCOUNT
SET BALANCE = BALANCE - 1000
WHERE ACC_NO = 101;

UPDATE BANK_ACCOUNT
SET BALANCE = BALANCE + 1000
WHERE ACC_NO = 102;

COMMIT;
select * from BANK_ACCOUNT;
-- savepoint example

START TRANSACTION;

UPDATE BANK_ACCOUNT
SET BALANCE = BALANCE - 500
WHERE ACC_NO = 101;

SAVEPOINT sp1;

UPDATE BANK_ACCOUNT
SET BALANCE = BALANCE - 500
WHERE ACC_NO = 101;

ROLLBACK TO sp1;

COMMIT;
SELECT * FROM BANK_ACCOUNT;


